### ISSUE TITLE
Code error in min_max_scaler in notebook #2

### ISSUE THREAD

**Issue by ChrisMuir** [ericmjl/data-testing-tutorial#12]
Within file `2-pytest-introduction.ipynb`, you have `test_min_max_scaler()`:
```python
def test_min_max_scaler():
    arr = np.array([1, 2, 3])  # set up the test with necessary variables.
    tfm = dfn.min_max_scaler(arr)  # collect the result into a variable
    assert tfm == np.array([0, 0.5, 1])  # assertion statements
    assert tfm.min() == 0  
    assert tfm.max() == 0 
```
I believe this line
```python 
assert tfm.max() == 0
``` 
should be 
```python 
assert tfm.max() == 1
```
It's correct in the code file `test_datafuncs_soln.py`, just not in the notebook file.

Also, really enjoyed the training session today, I learned a ton. Thanks for taking the time Eric.

**Comment by ericmjl** [comment]
Thanks a ton, @ChrisMuir!
