### ISSUE TITLE
Ecdf_scatter not imported/defined

### ISSUE THREAD

**Issue by Bachmann1234** [ericmjl/data-testing-tutorial#8]
<img width="832" alt="screenshot 2017-05-12 07 58 40" src="https://cloud.githubusercontent.com/assets/1521093/25997146/e48ef3d6-36e8-11e7-8568-70a8759a2897.png">

I actually dont know where this function comes from. Otherwise I would have PRed

**Comment by ericmjl** [comment]
Thanks @Bachmann1234! I think it's in one of the custom `.py` files I've got in the directory. I'll fix that, no worries about a PR here :smile:.

**Comment by ericmjl** [comment]
Actually, it's an old thing - I've updated that notebook. Git pull to see the new stuff!
